"use client"
import Link from "next/link"
import { usePathname } from "next/navigation";
import "./styles.css"

/* export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
} */

const navLinks=[
    {name: "Register", href: "/register"},
    {name: "Login", href: "/login"},
    {name: "Forgot Password", href: "/forgot-password"},
];

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const pathname = usePathname();
    return (
        <html lang="en">
            <body>
                 <div>
            {navLinks.map((link) =>{
                const isActive= pathname === link.href || (pathname.startsWith(link.href) && link.href !== "/");
                return(
                    <Link
                     className={isActive ? "linkOn" : "linkOff"}
                     href={link.href}
                     key={link.name}>
                        {link.name}
                    </Link>
                );
            })}
            {children}
        </div>
                {/* {children} */}
                <footer style={{backgroundColor: 'ghostwhite', padding: '1rem'}}>
                    <p>Footer</p>

                </footer>
            </body>
        </html>
       

    )
}
